name: Build and Release

on:
  push:
    tags:
      - "v*"  # Triggers only on version tags like v1.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Prevent automatic submodule checkout

      - name: Manually update submodules
        run: |
          git submodule update --init --recursive --depth=1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # Use any required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have dependencies

      - name: Run install
        run: python install.py  # Change to your actual script

      - name: Package artifact
        run: |
          mkdir -p release
          cp -r install/* release/  # Modify if needed
          tar -czf external_headeronlys.tar.gz -C release .
          zip -r external_headeronlys.zip release/

      - name: Upload tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact-tar
          path: external_headeronlys.tar.gz

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact-zip
          path: external_headeronlys.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub release creation

    steps:
      - name: Download tar.gz artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-artifact-tar
          path: .

      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-artifact-zip
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            external_headeronlys.tar.gz
            external_headeronlys.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
